language: ruby
os: linux
dist: xenial
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-lang-german
script:
- pdflatex Simpsons.tex
- bibtex "Simpsons"
- pdflatex Simpsons.tex
- pdflatex Simpsons.tex
- makeindex -g -s header.ist Simpsons.idx
- pdflatex Simpsons.tex
- pdflatex Simpsons.tex
deploy:
  provider: releases
  token:
    secure: LIGLOpAb9+LFm8ausWx5d5rjDY//GRC8Cc3iRlub0obPenrMmOW7owP8oy3U0TWLi3MvOHQJs+wm/BiZx1zXX+aYtCtbT6jd/FI5lxrwZDczU0NJ9uwmaXIeAoLFiRTw0Lz3wLhNTZlrrlTjXki3LI59N4jN0EmacXjILa2PKONc9tVCfDI+8Jyf0SJBzMr7uI9s5TqL5/jvyU617/An0TRLCYBVgfpsxRu950H6Eml69/BUBO8xJpxRuNT4j1ZGjgLWtAzncEsImJMItntGSt9GsN/gotQy3fQO/NGCyVhlkH0mknazx3FOdicRGh064v10LAD4pY1YyzOSsMSFTDxDmYZB7+TgzIlqV6PXlJzHeWaxVMeUNlG698YSHoRw8bevvqtwDW3vYljqTJSLb1OKSg0FY6gZBUa8OzV2++Ezcl8pN5F9wTISruDHOyVJtErQAYeD0smDBk42SzpZBg7CccZsdHoaH5i3EvCDr3zoJVtplR6LxIFzelCCprM2/o0vFZK4Ents0+fnm58GB7J9wWXIvS+tATmozC01yYuMSIk/PH7HkV7V/K3z6GRewynv+f6HNnHIX0DPPr12bIFyt3G5pkawqPKXw/bLeIhBfbfoUqL7tUo27cmuApgW/aH6SmIvnduH3tjlhWznKxaGVSFCQX/desQLRw1azWE=
  file: Simpsons.pdf
  cleanup: true
  draft: false
  prerelease: true
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
    repo: mflingelli/simpsons
    branch: feature/staffel31
env:
  global:
    secure: FpTArNfuEuiuN97E3tSN8DajrVYa2XKiVJGKKQ1GsAo+ZdXfFjiki6XyTxk59MxWOUpf91rTi4vC+nLxyZqlHriq82ihXivqe/OsIWOs1QoagUxs3swSoSkwqg6IXWn+9ujwshboLbyXKCsBTESx2CKdvCaPgKh+M1rwBB9WniLLm2baonKMl6qh7+RurgmtZt72WNGITuBDyPvOBWiKkVsBBUP1RcVQLAznC3XxKsy5X4977PJ25jaebXWqrvCkyHTF7xQRO0a8lTs/v8UlATTsFwCFB70kaHM/6JuBZsgx1PMVN8lROpCdfQmJYLaj73i49DLM4zHu1cQ/iBe6p9/M48nWlEyGkNjHIY+PxVokPdaqeWLwuD23QwxBjORBikGCrErFsk/FlEJ+fNwBwUZkD4d8RnAeRyexbE1VUXjKUWCjl2aSKbP6MFBPa1/o9SQAAeORisksdqlDGqA8YxlAm4lnxn7VzRK0YmO25m7/ckZOSKkS+uFspU5zIdE89sjyFE0x9NElsf9cs2+f5AGIwWNOo8sHvKJV9D+VPT/gZIuiUvT7EpAMT+FkmazXjvYgzjdOe9kaGlSJgZEQseNV6uW0YZv+qzPfZivl8y88EvETeIE9iy31A6W9DKyRhk/JwClmPDXGEl/+nKAcUa+q+EfUOOJAJbuYXDtP99U=
