name: Build Simpsons file
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            pdflatex Simpsons.tex
            bibtex Simpsons
            pdflatex Simpsons.tex
            pdflatex Simpsons.tex
            makeindex -g -s header.ist Simpsons.idx
            pdflatex Simpsons.tex
            pdflatex Simpsons.tex


