name: Hier sind die Simpsons
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: TeXLive installation
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-lang-german
      - name: LaTeX compilation
        run: |
          pdflatex Simpsons.tex > /dev/null 2>&1
          bibtex Simpsons
          pdflatex Simpsons.tex > /dev/null 2>&1
          pdflatex Simpsons.tex > /dev/null 2>&1
          makeindex -g -s header.ist Simpsons.idx
          pdflatex Simpsons.tex > /dev/null 2>&1
          pdflatex Simpsons.tex > /dev/null 2>&1
      - name: Draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: Simpsons.pdf


