name: Hier sind die Simpsons
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: TexLive compilation
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            pdflatex Simpsons.tex > /dev/null 2>&1
            bibtex Simpsons
            pdflatex Simpsons.tex > /dev/null 2>&1
            pdflatex Simpsons.tex > /dev/null 2>&1
            makeindex -g -s header.ist Simpsons.idx
            pdflatex Simpsons.tex > /dev/null 2>&1
            pdflatex Simpsons.tex > /dev/null 2>&1
      - name: Attaching ZIP archive
        uses: actions/upload-artifact@v2
        with:
          name: Simpsons
          path: Simpsons.pdf
      - name: Draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: Simpsons.pdf


